PromptAttNHP_train:
  base:
    use_torch: True
    is_training: True
    base_dir: './checkpoints/'
    batch_size: 256
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'ACC', 'RMSE' ]
    pretrained_model_dir: None
    pretrain_type: Prompt_only
  model:
    name: PromptAttNHP
    dataset_id: amazon
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    seed: 2019
    gpu: 0
    thinning_params:
      num_seq: 10
      num_sample: 1
      num_exp: 500
      look_ahead_time: 10
      patience_counter: 5
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5